name: Southvault
favicon: null
layout_spectrum: 0.73515
typography_spectrum: 0.89989
title: Southvault - the surveillance solution
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#110e09'
    - '#484137'
    - '#d6c7b2'
    - '#fae211'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
